name: Action flow

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: :|
          pwd
          ls -a
      - name: check out
        uses: actions/checkout@v1
      - name: python Command
        run: |
          sudo apt-get install python3.7
          sudo rm /usr/bin/python2.7

         
      - name: simple js action
        id: greet
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
            playbookName: 'hardcoded_main.yml'
      - name: Log the time
        run: echo "{{steps.greet.outputs.time}}"