name: Action flow

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: :|
          pwd
          ls -a
      - name: check out
        uses: actions/checkout@v1
      - name: python Command
        run: |
          sudo apt-get install python3.7
          ansible --version | grep "python version"
          python version = 3.6.2 (default, Sep 22 2017, 08:28:09) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]

         
      - name: simple js action
        id: greet
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
            playbookName: 'hardcoded_main.yml'
      - name: Log the time
        run: echo "{{steps.greet.outputs.time}}"