name: Action flow

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: :|
          pwd
          ls -a
      - name: check out
        uses: actions/checkout@v1
      - name: python Command
        run: |
          import platform
          print(platform.processor())
          pip3 install ansible
        shell: python
      - name: simple js action
        id: greet
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
            playbookName: 'hardcoded_main.yml'
      - name: Log the time
        run: echo "{{steps.greet.outputs.time}}"