name: Action flow

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: simple js action
        id: greet
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
            playbookName: 'https://github.com/nm-saravanan/simple-action/blob/master/play1.yml'
      - name: Log the time
        run: echo "{{steps.greet.outputs.time}}"