name: Action flow

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9.0-buster
    steps:
      - name: List files
        run: :|
          pwd
          ls -a
      - name: check out
        uses: actions/checkout@v1
         
      - name: simple js action
        id: greet
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
            playbookName: 'hardcoded_main.yml'
      - name: Log the time
        run: echo "{{steps.greet.outputs.time}}"