name: Action flow

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: simple js action
        id: greet
        uses: actions/hello-world-javascript-action
        with:
            who-to-greet: Saravanan
      - name: Log the time
        run: echo "{{steps.greet.outputs.time}}"