on:

  repository_dispatch:
    types: [build]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: Azure/docker-login@v1
      with:
        login-server: contoso.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: azure/setup-kubectl@v1
      with:
        #version: '<version>' # default is latest stable
        id: install
    - uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: ${{ secrets.K8S_URL }} 
        k8s-secret: ${{ secrets.K8S_SECRECT }}
        id: setcontext
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
        resource-group: 'digitalai-demo-23-11-2020'
        cluster-name: 'digitalai-cluster-demo'
        id: login

    - name: Set imagePullSecret
      uses: azure/k8s-create-secret@v1
      with:
        namespace: 'default'
        container-registry-url: 'containerregistry.contoso.com'
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: 'contoso-cr'
        id: create-secret

    - uses: Azure/k8s-deploy@v1
      with:
        namespace: 'default'
        manifests: |
          k8s/redis-deployment.yaml
          k8s/redis-cluster-ip-service.yaml
          k8s/client-cluster-ip-service.yaml
          k8s/client-deployment.yaml
        imagepullsecrets: |
          contoso-cr
        kubectl-version: 'latest'

    - uses: azure/setup-helm@v1
      with:
        id: install
 