on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    #- uses: Azure/docker-login@v1
     # with:
      #  login-server: contoso.azurecr.io
       # username: ${{ secrets.REGISTRY_USERNAME }}
        #password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: azure/setup-kubectl@v1
      with:
        #version: '<version>' # default is latest stable
        id: install
    - uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: ${{ secrets.K8S_URL }} 
        k8s-secret: ${{ secrets.K8S_SECRECT }}
        id: setcontext
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
        resource-group: 'cloud-shell-storage-centralindia'
        cluster-name: 'demo-24-11on'
        id: login
        run: |
          echo: REGISTRY_USERNAME::: ${{ secrets.REGISTRY_USERNAME }}

    - name: Set imagePullSecret
      uses: azure/k8s-create-secret@v1
      with:
        namespace: 'default'
        container-registry-url: 'containerregistry.contoso.com'
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: 'contoso-cr'
        id: create-secret

    - uses: Azure/k8s-deploy@v1
      with:
        namespace: 'default'
        manifests: |
         
          k8s/aks-helloworld-one.yaml
          k8s/aks-helloworld-two.yaml
          k8s/hello-world-ingress.yaml
          
          
        imagepullsecrets: |
          contoso-cr
        kubectl-version: 'latest'

    - uses: azure/setup-helm@v1
      with:
        id: install
   
      
 
 
