on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: Azure/docker-login@v1
      with:
        login-server: contoso.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: azure/setup-kubectl@v1
      with:
        #version: '<version>' # default is latest stable
        id: install
    - uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: ${{ secrets.K8S_URL }} 
        k8s-secret: ${{ secrets.K8S_SECRECT }}
        id: setcontext
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
        resource-group: 'digitalai-demo-23-11-2020'
        cluster-name: 'digitalai-cluster-demo'
        id: login

    - name: Set imagePullSecret
      uses: azure/k8s-create-secret@v1
      with:
        namespace: 'myapp'
        container-registry-url: 'index.docker.io'
        container-registry-username: ${{ secrets.DOCKER_HUB_USERNAME }}
        container-registry-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        secret-name: 'contoso-cr'
        id: create-secret
    - run: |
        docker build . -t contoso.azurecr.io/k8sdemo:${{ github.sha }}
        docker push contoso.azurecr.io/k8sdemo:${{ github.sha }}