on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: Azure/docker-login@v1
      with:
        login-server: contoso.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: azure/setup-kubectl@v1
      with:
        #version: '<version>' # default is latest stable
        id: install
    - uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: ${{ K8S_URL }} 
        k8s-secret: ${{ K8S_SECRECT }}
        id: setcontext
    - run: |
        docker build . -t contoso.azurecr.io/k8sdemo:${{ github.sha }}
        docker push contoso.azurecr.io/k8sdemo:${{ github.sha }}