name: Docker hub login 
on:

  repository_dispatch:
    types: [build]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
     - name: Login to DockerHub
       uses: docker/login-action@v1 
       with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
     - name: Docker pull
       run: docker pull registry.hub.docker.com/library/busybox
     - name: mysql version
       run: mysql -V
     