name: Shell Command
on:
  repository_dispatch:
    types: [build]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: print a strng
        run: echo "Hello......"
      - name: multi script
        run: |
          node -v
          npm -v
