name: Shell Command
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{github.event.client_payload.case}}
      - name: varibales
        run: echo "my var $GITHUB_ACTOR ${{secrets}}"
      - name: print a strng
        run: echo "Hello......"
      - name: multi script
        run: |
          node -v
          npm -v
