name: Shell Command
on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: print a strng
        run: echo "Hello......"
      - name: multi script
        run: |
          node -v
          npm -v
